/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Launcher;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import static javax.swing.SwingConstants.CENTER;

/**
 *
 * @author javierballesteroscarcamo
 */
public class launcherBase extends javax.swing.JFrame {
    
    Dimension tamañoBotones = new Dimension(90,90);
    JLabel[] botones;
    String[] rutasBotones;
    
  
    private launcherBase thisFrame;
    
    public launcherBase() {
        
        initComponents();
        thisFrame = this;
        vistaHome vista = new vistaHome(thisFrame);
        ShowPanel(vista);
        
        
        
        
        botones = new JLabel[]{Escudo1,Escudo2,Escudo3,Escudo4,Escudo5,Escudo6,Escudo7,Escudo8,Escudo9,Escudo10,Escudo11,Escudo12,Escudo13,Escudo14};
        rutasBotones = new String[]{
            
            "src/images/LauncherButton8.png",
            "src/images/LauncherButton0.png",
            "src/images/LauncherButton1.png",
            "src/images/LauncherButton2.png",
            "src/images/LauncherButton3.png",
            "src/images/LauncherButton4.png",
            "src/images/LauncherButton5.png",
            "src/images/LauncherButton6.png",
            "src/images/LauncherButton7.png",
            "src/images/LauncherButton13.png",
            "src/images/LauncherButton9.png",
            "src/images/LauncherButton10.png",
            "src/images/LauncherButton11.png",
            "src/images/LauncherButton12.png",
                
           
            
        };
        
        for(int i = 0; i <botones.length; i++){
            
            utilidades.reescala(botones[i], rutasBotones[i], tamañoBotones);
            
        
        }
        
      
        
        
}
    
    
    void ShowPanel(JPanel page){
        page.setSize(1550, 880);
        page.setLocation(0, 0);
        
        content.removeAll();
        content.add(page, content, CENTER);
        content.revalidate();
        content.repaint();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        bg = new javax.swing.JPanel();
        panelEscudos = new javax.swing.JPanel();
        Escudo1 = new javax.swing.JLabel();
        Escudo2 = new javax.swing.JLabel();
        Escudo3 = new javax.swing.JLabel();
        Escudo4 = new javax.swing.JLabel();
        Escudo5 = new javax.swing.JLabel();
        Escudo6 = new javax.swing.JLabel();
        Escudo7 = new javax.swing.JLabel();
        Escudo8 = new javax.swing.JLabel();
        Escudo9 = new javax.swing.JLabel();
        Escudo10 = new javax.swing.JLabel();
        Escudo11 = new javax.swing.JLabel();
        Escudo12 = new javax.swing.JLabel();
        Escudo13 = new javax.swing.JLabel();
        Escudo14 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        base = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(1920, 1080));
        bg.setPreferredSize(new java.awt.Dimension(1920, 1080));
        bg.setRequestFocusEnabled(false);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEscudos.setOpaque(false);
        panelEscudos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 20));

        Escudo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Escudo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton8.png"))); // NOI18N
        Escudo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo1.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo1.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo1.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo1MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo1);

        Escudo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Escudo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton0.png"))); // NOI18N
        Escudo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo2.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo2.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo2.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo2MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo2);

        Escudo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton1.png"))); // NOI18N
        Escudo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo3.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo3.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo3.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo3MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo3);

        Escudo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton2.png"))); // NOI18N
        Escudo4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo4.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo4.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo4.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo4MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo4);

        Escudo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton3.png"))); // NOI18N
        Escudo5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo5.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo5.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo5.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo5MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo5);

        Escudo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton4.png"))); // NOI18N
        Escudo6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo6.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo6.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo6.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo6MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo6);

        Escudo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton5.png"))); // NOI18N
        Escudo7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo7.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo7.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo7.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo7MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo7);

        Escudo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton6.png"))); // NOI18N
        Escudo8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo8.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo8.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo8.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo8MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo8);

        Escudo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton7.png"))); // NOI18N
        Escudo9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo9.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo9.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo9.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo9MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo9);

        Escudo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton13.png"))); // NOI18N
        Escudo10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo10.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo10.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo10.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo10MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo10);

        Escudo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton9.png"))); // NOI18N
        Escudo11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo11.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo11.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo11.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo11MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo11);

        Escudo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton10.png"))); // NOI18N
        Escudo12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo12.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo12.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo12.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo12MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo12);

        Escudo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton11.png"))); // NOI18N
        Escudo13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo13.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo13.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo13.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo13MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo13);

        Escudo14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Escudo14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LauncherButton12.png"))); // NOI18N
        Escudo14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Escudo14.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo14.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo14.setPreferredSize(new java.awt.Dimension(100, 100));
        Escudo14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Escudo14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Escudo14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Escudo14MouseExited(evt);
            }
        });
        panelEscudos.add(Escudo14);

        bg.add(panelEscudos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 1552, 132));

        content.setBackground(new java.awt.Color(10, 38, 72));
        content.setMaximumSize(new java.awt.Dimension(90, 90));
        content.setMinimumSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1548, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 1548, 900));
        content.getAccessibleContext().setAccessibleName("");

        base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoBase.png"))); // NOI18N
        bg.add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }//GEN-END:initComponents

    private void Escudo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo1MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo1MouseClicked

    private void Escudo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo2MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo2MouseClicked

    private void Escudo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo3MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo3MouseClicked

    private void Escudo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo4MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo4MouseClicked

    private void Escudo5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo5MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo5MouseClicked

    private void Escudo6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo6MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo6MouseClicked

    private void Escudo7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo7MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo7MouseClicked

    private void Escudo8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo8MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo8MouseClicked

    private void Escudo9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo9MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo9MouseClicked

    private void Escudo10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo10MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo10MouseClicked

    private void Escudo11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo11MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo11MouseClicked

    private void Escudo12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo12MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo12MouseClicked

    private void Escudo13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo13MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo13MouseClicked

    private void Escudo14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo14MouseClicked
        vistaHome vista = new vistaHome (thisFrame);
        ShowPanel (vista);
    }//GEN-LAST:event_Escudo14MouseClicked

    private void Escudo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo1MouseEntered
        utilidades.reescala(Escudo1, rutasBotones[0]);
        
    }//GEN-LAST:event_Escudo1MouseEntered

    private void Escudo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo1MouseExited
         utilidades.reescala(Escudo1, rutasBotones[0], tamañoBotones);
    }//GEN-LAST:event_Escudo1MouseExited

    private void Escudo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo2MouseEntered
        utilidades.reescala(Escudo2, rutasBotones[1]);
    }//GEN-LAST:event_Escudo2MouseEntered

    private void Escudo3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo3MouseExited
        utilidades.reescala(Escudo3, rutasBotones[2], tamañoBotones);
    }//GEN-LAST:event_Escudo3MouseExited

    private void Escudo4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo4MouseEntered
        utilidades.reescala(Escudo4, rutasBotones[3]);
    }//GEN-LAST:event_Escudo4MouseEntered

    private void Escudo4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo4MouseExited
        utilidades.reescala(Escudo4, rutasBotones[3], tamañoBotones);
    }//GEN-LAST:event_Escudo4MouseExited

    private void Escudo5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo5MouseEntered
        utilidades.reescala(Escudo5, rutasBotones[4]);
    }//GEN-LAST:event_Escudo5MouseEntered

    private void Escudo5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo5MouseExited
        utilidades.reescala(Escudo5, rutasBotones[4], tamañoBotones);
    }//GEN-LAST:event_Escudo5MouseExited

    private void Escudo6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo6MouseEntered
        utilidades.reescala(Escudo6, rutasBotones[5]);
    }//GEN-LAST:event_Escudo6MouseEntered

    private void Escudo6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo6MouseExited
        utilidades.reescala(Escudo6, rutasBotones[5], tamañoBotones);
    }//GEN-LAST:event_Escudo6MouseExited

    private void Escudo7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo7MouseEntered
        utilidades.reescala(Escudo7, rutasBotones[6]);
    }//GEN-LAST:event_Escudo7MouseEntered

    private void Escudo7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo7MouseExited
        utilidades.reescala(Escudo7, rutasBotones[6], tamañoBotones);
    }//GEN-LAST:event_Escudo7MouseExited

    private void Escudo8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo8MouseEntered
        utilidades.reescala(Escudo8, rutasBotones[7]);
    }//GEN-LAST:event_Escudo8MouseEntered

    private void Escudo8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo8MouseExited
        utilidades.reescala(Escudo8, rutasBotones[7], tamañoBotones);
    }//GEN-LAST:event_Escudo8MouseExited

    private void Escudo9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo9MouseEntered
        utilidades.reescala(Escudo9, rutasBotones[8]);
    }//GEN-LAST:event_Escudo9MouseEntered

    private void Escudo9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo9MouseExited
        utilidades.reescala(Escudo9, rutasBotones[8], tamañoBotones);
    }//GEN-LAST:event_Escudo9MouseExited

    private void Escudo10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo10MouseEntered
        utilidades.reescala(Escudo10, rutasBotones[9]);
    }//GEN-LAST:event_Escudo10MouseEntered

    private void Escudo10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo10MouseExited
        utilidades.reescala(Escudo10, rutasBotones[9], tamañoBotones);
    }//GEN-LAST:event_Escudo10MouseExited

    private void Escudo11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo11MouseEntered
        utilidades.reescala(Escudo11, rutasBotones[10]);
    }//GEN-LAST:event_Escudo11MouseEntered

    private void Escudo11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo11MouseExited
        utilidades.reescala(Escudo11, rutasBotones[10], tamañoBotones);
    }//GEN-LAST:event_Escudo11MouseExited

    private void Escudo12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo12MouseEntered
        utilidades.reescala(Escudo12, rutasBotones[11]);
    }//GEN-LAST:event_Escudo12MouseEntered

    private void Escudo12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo12MouseExited
        utilidades.reescala(Escudo12, rutasBotones[11], tamañoBotones);
    }//GEN-LAST:event_Escudo12MouseExited

    private void Escudo13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo13MouseExited
        utilidades.reescala(Escudo13, rutasBotones[12], tamañoBotones);
    }//GEN-LAST:event_Escudo13MouseExited

    private void Escudo2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo2MouseExited
        utilidades.reescala(Escudo2, rutasBotones[1], tamañoBotones);
    }//GEN-LAST:event_Escudo2MouseExited

    private void Escudo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo3MouseEntered
       utilidades.reescala(Escudo3, rutasBotones[2]);
    }//GEN-LAST:event_Escudo3MouseEntered

    private void Escudo14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo14MouseEntered
       utilidades.reescala(Escudo14, rutasBotones[13]);
    }//GEN-LAST:event_Escudo14MouseEntered

    private void Escudo13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo13MouseEntered
        utilidades.reescala(Escudo13, rutasBotones[12]);
    }//GEN-LAST:event_Escudo13MouseEntered

    private void Escudo14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Escudo14MouseExited
        utilidades.reescala(Escudo14, rutasBotones[13], tamañoBotones);
    }//GEN-LAST:event_Escudo14MouseExited

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new launcherBase().setVisible(true);
                
                
            }
        });
    }
            private void SetImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Escudo1;
    private javax.swing.JLabel Escudo10;
    private javax.swing.JLabel Escudo11;
    private javax.swing.JLabel Escudo12;
    private javax.swing.JLabel Escudo13;
    private javax.swing.JLabel Escudo14;
    private javax.swing.JLabel Escudo2;
    private javax.swing.JLabel Escudo3;
    private javax.swing.JLabel Escudo4;
    private javax.swing.JLabel Escudo5;
    private javax.swing.JLabel Escudo6;
    private javax.swing.JLabel Escudo7;
    private javax.swing.JLabel Escudo8;
    private javax.swing.JLabel Escudo9;
    private javax.swing.JLabel base;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel content;
    private javax.swing.JPanel panelEscudos;
    // End of variables declaration//GEN-END:variables

    private void setLocation(String srcimagesFondoBasepng) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
