/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Launcher;

import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import org.json.JSONException;

/**
 *
 * @author javierballesteroscarcamo
 */
public class vistaHome extends javax.swing.JPanel {
    
    
    
    
    
    public int indexGrado;
    
    Dimension tamañoBotones = new Dimension(381,291);
    JLabel[] botones;
    String[] rutasBotones;
    
    
   

    private launcherBase baseFrame;
    private launcherBase[] configs;
   
    
    public vistaHome(launcherBase frame) {
        this.baseFrame = frame;
        initComponents();
        botones = new JLabel[]{};
        rutasBotones = new String[]{
            
            "src/images/HomeButton0.png",
            "src/images/HomeButton1.png",
            "src/images/HomeButton2.png",
            "src/images/HomeButton3.png",
            "src/images/HomeButton4.png",
            "src/images/HomeButton5.png",
    
        };
        for(int i = 0; i <botones.length; i++)
        {
            utilidades.reescala(botones[i], rutasBotones[i], tamañoBotones);
        }
            
        
    }
    public static void vistaHome(String[] args){
        new vistaGame().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        Btn1 = new javax.swing.JLabel();
        Btn2 = new javax.swing.JLabel();
        Btn3 = new javax.swing.JLabel();
        Btn4 = new javax.swing.JLabel();
        Btn5 = new javax.swing.JLabel();
        Btn6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1480, 880));
        setMinimumSize(new java.awt.Dimension(1480, 880));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1480, 880));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HomeButton0.png"))); // NOI18N
        Btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn1MouseExited(evt);
            }
        });
        add(Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 100, 390, -1));

        Btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HomeButton1.png"))); // NOI18N
        Btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn2.setMaximumSize(new java.awt.Dimension(381, 291));
        Btn2.setMinimumSize(new java.awt.Dimension(381, 291));
        Btn2.setPreferredSize(new java.awt.Dimension(381, 291));
        Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn2MouseExited(evt);
            }
        });
        add(Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 100, 390, -1));

        Btn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HomeButton2.png"))); // NOI18N
        Btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn3MouseExited(evt);
            }
        });
        add(Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 100, 391, -1));

        Btn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HomeButton3.png"))); // NOI18N
        Btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn4.setMaximumSize(new java.awt.Dimension(381, 291));
        Btn4.setMinimumSize(new java.awt.Dimension(381, 291));
        Btn4.setPreferredSize(new java.awt.Dimension(381, 291));
        Btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn4MouseExited(evt);
            }
        });
        add(Btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 488, 390, -1));

        Btn5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HomeButton4.png"))); // NOI18N
        Btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn5.setMaximumSize(new java.awt.Dimension(381, 291));
        Btn5.setMinimumSize(new java.awt.Dimension(381, 291));
        Btn5.setPreferredSize(new java.awt.Dimension(381, 291));
        Btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn5MouseExited(evt);
            }
        });
        add(Btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 488, 401, -1));

        Btn6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HomeButton5.png"))); // NOI18N
        Btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn6MouseExited(evt);
            }
        });
        add(Btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 488, 391, -1));
    }//GEN-END:initComponents
    
    private void Btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseClicked
        vistaGame game = new vistaGame(baseFrame);
        
        try {
            game.rutasImagenes = utilidades.CrearListaString("src/images/", utilidades.ImagenJuego(indexGrado, 0), ".png", 5).toArray(new String[5]);
            game.NombreJuego = utilidades.NombreJuego(indexGrado, 0);
            game.DescripcionJuego = utilidades.DescripcionJuego(indexGrado, 0);
        } catch (IOException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        game.ActualizarGame();
        baseFrame.ShowPanel(game);
        
    }//GEN-LAST:event_Btn1MouseClicked

    private void Btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseClicked
        vistaGame game = new vistaGame(baseFrame);
        
        try {
            game.rutasImagenes = utilidades.CrearListaString("src/images/", utilidades.ImagenJuego(indexGrado, 1), ".png", 5).toArray(new String[5]);
            game.NombreJuego = utilidades.NombreJuego(indexGrado, 1);
            game.DescripcionJuego = utilidades.DescripcionJuego(indexGrado, 1);
        } catch (IOException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        game.ActualizarGame();
        baseFrame.ShowPanel(game);
        
    }//GEN-LAST:event_Btn2MouseClicked

    private void Btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseClicked
        vistaGame game = new vistaGame(baseFrame);
        try {
            game.rutasImagenes = utilidades.CrearListaString("src/images/", utilidades.ImagenJuego(indexGrado, 2), ".png", 5).toArray(new String[5]);
            game.NombreJuego = utilidades.NombreJuego(indexGrado, 2);
            game.DescripcionJuego = utilidades.DescripcionJuego(indexGrado, 2);
        } catch (IOException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        game.ActualizarGame();
        baseFrame.ShowPanel(game);
    }//GEN-LAST:event_Btn3MouseClicked

    private void Btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn4MouseClicked
        vistaGame game = new vistaGame(baseFrame);
        try {
            game.rutasImagenes = utilidades.CrearListaString("src/images/", utilidades.ImagenJuego(indexGrado, 3), ".png", 5).toArray(new String[5]);
            game.NombreJuego = utilidades.NombreJuego(indexGrado, 3);
            game.DescripcionJuego = utilidades.DescripcionJuego(indexGrado, 3);
        } catch (IOException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        game.ActualizarGame();
        baseFrame.ShowPanel(game);
    }//GEN-LAST:event_Btn4MouseClicked

    private void Btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseClicked
        vistaGame game = new vistaGame(baseFrame);
        try {
            game.rutasImagenes = utilidades.CrearListaString("src/images/", utilidades.ImagenJuego(indexGrado, 4), ".png", 5).toArray(new String[5]);
            game.NombreJuego = utilidades.NombreJuego(indexGrado, 4);
            game.DescripcionJuego = utilidades.DescripcionJuego(indexGrado, 4);
        } catch (IOException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        game.ActualizarGame();
        baseFrame.ShowPanel(game);
    }//GEN-LAST:event_Btn5MouseClicked

    private void Btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseClicked
        vistaGame game = new vistaGame(baseFrame);
        try {
            game.rutasImagenes = utilidades.CrearListaString("src/images/", utilidades.ImagenJuego(indexGrado, 5), ".png", 5).toArray(new String[5]);
            game.NombreJuego = utilidades.NombreJuego(indexGrado, 5);
            game.DescripcionJuego = utilidades.DescripcionJuego(indexGrado, 5);
        } catch (IOException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(vistaHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        game.ActualizarGame();
        baseFrame.ShowPanel(game);
    }//GEN-LAST:event_Btn6MouseClicked

    private void Btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseEntered
        utilidades.reescala(Btn1, rutasBotones[0]);
    }//GEN-LAST:event_Btn1MouseEntered

    private void Btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseExited
        utilidades.reescala(Btn1, rutasBotones[0], tamañoBotones);
    }//GEN-LAST:event_Btn1MouseExited

    private void Btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseEntered
        utilidades.reescala(Btn2, rutasBotones[1]);
    }//GEN-LAST:event_Btn2MouseEntered

    private void Btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseExited
        utilidades.reescala(Btn2, rutasBotones[1], tamañoBotones);
    }//GEN-LAST:event_Btn2MouseExited

    private void Btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseEntered
        utilidades.reescala(Btn3, rutasBotones[2]);
    }//GEN-LAST:event_Btn3MouseEntered

    private void Btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseExited
        utilidades.reescala(Btn3, rutasBotones[2], tamañoBotones);
    }//GEN-LAST:event_Btn3MouseExited

    private void Btn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn4MouseEntered
        utilidades.reescala(Btn4, rutasBotones[3]);
    }//GEN-LAST:event_Btn4MouseEntered

    private void Btn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn4MouseExited
        utilidades.reescala(Btn4, rutasBotones[3], tamañoBotones);
    }//GEN-LAST:event_Btn4MouseExited

    private void Btn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseEntered
        utilidades.reescala(Btn5, rutasBotones[4]);
    }//GEN-LAST:event_Btn5MouseEntered

    private void Btn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseExited
        utilidades.reescala(Btn5, rutasBotones[4], tamañoBotones);
    }//GEN-LAST:event_Btn5MouseExited

    private void Btn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseEntered
        utilidades.reescala(Btn6, rutasBotones[5]);
    }//GEN-LAST:event_Btn6MouseEntered

    private void Btn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseExited
        utilidades.reescala(Btn6, rutasBotones[5], tamañoBotones);
    }//GEN-LAST:event_Btn6MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn1;
    private javax.swing.JLabel Btn2;
    private javax.swing.JLabel Btn3;
    private javax.swing.JLabel Btn4;
    private javax.swing.JLabel Btn5;
    private javax.swing.JLabel Btn6;
    // End of variables declaration//GEN-END:variables


}
