/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Launcher;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.json.JSONException;

/**
 *
 * @author javierballesteroscarcamo
 */
public class vistaGame extends javax.swing.JPanel {
    
    
    
    int contador=0;
    

        Dimension tamañoComenzar = new Dimension (253,44);
        JLabel[] botonComenzar;
        String[] rutaComenzar;
        
        Dimension tamañoFlechas = new Dimension (22,35);
        JLabel[] botonFlechas;
        String[] rutaFlechas;
        
        Dimension tamañoEmbarque = new Dimension (891,525); 
        public String[] rutasImagenes;
        
        
        
        Dimension tamañoPuntos = new Dimension (16,17);
        String [] rutaPuntos = {
            
        "src/images/PuntoCarruselEmpty.png",
        "src/images/PuntoCarruselFilled.png",
        };
        
    
    
    String NombreJuego;
    String DescripcionJuego;
     
    
   
   
   
                            
                             
    
    

    /**
     * Creates new form vistaGame
     * @param thisFrame
     */
    public vistaGame(launcherBase thisFrame) {
        initComponents();
        
        
        
        botonComenzar = new JLabel [] {BtnComenzar};
        rutaComenzar = new String [] {
            
            "src/images/Comenzar.png"
        };
        
        
                                       
        { 
            utilidades.reescala(botonComenzar[0], rutaComenzar[0], tamañoComenzar);
            
        
            }
        
      
        botonFlechas = new JLabel [] {FlechaIzq,FlechaDer};
        rutaFlechas = new String [] {
            
            "src/images/Flecha izquierda.png",
            "src/images/Flecha derecha.png",
        };
        
        for(int i = 0; i <botonFlechas.length; i++)
        
        {
    
        utilidades.reescala(botonFlechas[i], rutaFlechas[i], tamañoFlechas);
        
        
        
    }
        
        
}
    public void ActualizarGame (){
        SetImageLabel(ContentEmbarque, rutasImagenes[contador],tamañoEmbarque);
        jTextField1.setText(NombreJuego);
        Text.setText(DescripcionJuego);
        
    }

    vistaGame() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    

 


    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        bgGame = new javax.swing.JPanel();
        BtnComenzar = new javax.swing.JLabel();
        ContentEmbarque = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        Linea = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        basePuntos = new javax.swing.JPanel();
        Punto1 = new javax.swing.JLabel();
        Punto2 = new javax.swing.JLabel();
        Punto3 = new javax.swing.JLabel();
        Punto4 = new javax.swing.JLabel();
        Punto5 = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        FlechaIzq = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FlechaDer = new javax.swing.JLabel();

        setOpaque(false);

        bgGame.setForeground(new java.awt.Color(51, 51, 55));
        bgGame.setToolTipText("");
        bgGame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bgGame.setOpaque(false);
        bgGame.setRequestFocusEnabled(false);
        bgGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnComenzar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Comenzar.png"))); // NOI18N
        BtnComenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnComenzar.setMaximumSize(new java.awt.Dimension(233, 24));
        BtnComenzar.setMinimumSize(new java.awt.Dimension(233, 24));
        BtnComenzar.setPreferredSize(new java.awt.Dimension(233, 24));
        BtnComenzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnComenzarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnComenzarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnComenzarMouseExited(evt);
            }
        });
        bgGame.add(BtnComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 790, 292, 52));

        ContentEmbarque.setBackground(new java.awt.Color(10, 38, 72));
        ContentEmbarque.setForeground(new java.awt.Color(10, 38, 72));
        ContentEmbarque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContentEmbarque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Embarque0.png"))); // NOI18N
        bgGame.add(ContentEmbarque, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 80, 892, 500));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cuadrado fondo enfocado.png"))); // NOI18N
        bgGame.add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 120, 768, 416));

        Fondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cuadrado fondo enfocado.png"))); // NOI18N
        bgGame.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 120, 728, 416));

        Linea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Barrita aislada descripción.png"))); // NOI18N
        bgGame.add(Linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 624, 8, 40));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Embarque y desembarque en helicoptero");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(51, 51, 55));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField1.setDisabledTextColor(new java.awt.Color(51, 51, 55));
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        bgGame.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 628, 1080, 36));

        basePuntos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        basePuntos.setOpaque(false);

        Punto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Punto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PuntoCarruselFilled.png"))); // NOI18N
        basePuntos.add(Punto1);

        Punto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Punto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PuntoCarruselEmpty.png"))); // NOI18N
        basePuntos.add(Punto2);

        Punto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Punto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PuntoCarruselEmpty.png"))); // NOI18N
        basePuntos.add(Punto3);

        Punto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Punto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PuntoCarruselEmpty.png"))); // NOI18N
        basePuntos.add(Punto4);

        Punto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Punto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PuntoCarruselEmpty.png"))); // NOI18N
        basePuntos.add(Punto5);

        bgGame.add(basePuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 592, 112, 24));

        Text.setBackground(new java.awt.Color(255, 255, 255));
        Text.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 255, 255));
        Text.setText("<html>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua <br> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<br><br> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.<br> Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.<html>");
        bgGame.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 668, 948, 164));

        FlechaIzq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FlechaIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Flecha izquierda.png"))); // NOI18N
        FlechaIzq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FlechaIzq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlechaIzqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FlechaIzqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FlechaIzqMouseExited(evt);
            }
        });
        bgGame.add(FlechaIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 304, 32, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        bgGame.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 88, 848, 484));

        FlechaDer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FlechaDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Flecha derecha.png"))); // NOI18N
        FlechaDer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FlechaDer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlechaDerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FlechaDerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FlechaDerMouseExited(evt);
            }
        });
        bgGame.add(FlechaDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1276, 312, 32, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgGame, javax.swing.GroupLayout.DEFAULT_SIZE, 1480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }//GEN-END:initComponents

    private void SetImageLabel(JLabel labelName, String root, Dimension dimension) {
        ImageIcon image = new ImageIcon (root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(dimension.width, dimension.height, Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BtnComenzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComenzarMouseClicked
        try {
            String rutaJuego = utilidades.RutaJuego(1, 1);
            if (Desktop.isDesktopSupported()){
                Desktop.getDesktop().open(new java.io.File(rutaJuego));   
            } else{
                System.out.println("No se puede abrir el juego.");
            }
        } catch (IOException ex) {
            Logger.getLogger(vistaGame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(vistaGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnComenzarMouseClicked

    private void FlechaIzqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlechaIzqMouseClicked
          if(contador<=0) {
            contador=4;
        }
          else{
              contador--;
          }
          SetImageLabel(ContentEmbarque, rutasImagenes[contador],tamañoEmbarque);
          
           
switch (contador){
              case 4 ->{
                  utilidades.reescala(Punto1, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto2, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto3, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto4, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto5, rutaPuntos[1], tamañoPuntos);
                  
              }
              case 3 ->{
                  utilidades.reescala(Punto1, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto2, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto3, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto4, rutaPuntos[1], tamañoPuntos);
                  utilidades.reescala(Punto5, rutaPuntos[0], tamañoPuntos);
                  
              }  
              case 2 ->{
                  utilidades.reescala(Punto1, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto2, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto3, rutaPuntos[1], tamañoPuntos);
                  utilidades.reescala(Punto4, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto5, rutaPuntos[0], tamañoPuntos);
                  
              }   
               case 1 ->{
                  utilidades.reescala(Punto1, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto2, rutaPuntos[1], tamañoPuntos);
                  utilidades.reescala(Punto3, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto4, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto5, rutaPuntos[0], tamañoPuntos);
                  
              } 
               case 0 ->{
                  utilidades.reescala(Punto1, rutaPuntos[1], tamañoPuntos);
                  utilidades.reescala(Punto2, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto3, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto4, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto5, rutaPuntos[0], tamañoPuntos);
                  
                  
              } 
           
                
              
          }
    }//GEN-LAST:event_FlechaIzqMouseClicked

    private void FlechaDerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlechaDerMouseClicked
          if(contador==4) {
            contador=0;
        }
          else {
              contador++;
          }
          SetImageLabel(ContentEmbarque, rutasImagenes[contador],tamañoEmbarque);
          
          switch (contador){
              case 0 ->{
                  utilidades.reescala(Punto1, rutaPuntos[1], tamañoPuntos);
                  utilidades.reescala(Punto2, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto3, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto4, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto5, rutaPuntos[0], tamañoPuntos);
                  
              }
              case 1 ->{
                  utilidades.reescala(Punto1, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto2, rutaPuntos[1], tamañoPuntos);
                  utilidades.reescala(Punto3, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto4, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto5, rutaPuntos[0], tamañoPuntos);
                  
              }  
              case 2 ->{
                  utilidades.reescala(Punto1, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto2, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto3, rutaPuntos[1], tamañoPuntos);
                  utilidades.reescala(Punto4, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto5, rutaPuntos[0], tamañoPuntos);
                  
              }   
               case 3 ->{
                  utilidades.reescala(Punto1, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto2, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto3, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto4, rutaPuntos[1], tamañoPuntos);
                  utilidades.reescala(Punto5, rutaPuntos[0], tamañoPuntos);
                  
              } 
               case 4 ->{
                  utilidades.reescala(Punto1, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto2, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto3, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto4, rutaPuntos[0], tamañoPuntos);
                  utilidades.reescala(Punto5, rutaPuntos[1], tamañoPuntos);
                  
                  
              } 
           
                
              
          }
  
        
          
          
      
    }//GEN-LAST:event_FlechaDerMouseClicked

    private void BtnComenzarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComenzarMouseEntered
        utilidades.reescala(BtnComenzar, rutaComenzar[0]);
    }//GEN-LAST:event_BtnComenzarMouseEntered

    private void BtnComenzarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComenzarMouseExited
        utilidades.reescala(BtnComenzar, rutaComenzar[0], tamañoComenzar);
    }//GEN-LAST:event_BtnComenzarMouseExited

    private void FlechaIzqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlechaIzqMouseEntered
        utilidades.reescala(FlechaIzq, rutaFlechas[0]);
    }//GEN-LAST:event_FlechaIzqMouseEntered

    private void FlechaIzqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlechaIzqMouseExited
        utilidades.reescala(FlechaIzq, rutaFlechas[0], tamañoFlechas);
    }//GEN-LAST:event_FlechaIzqMouseExited

    private void FlechaDerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlechaDerMouseEntered
        utilidades.reescala(FlechaDer, rutaFlechas[1]);
    }//GEN-LAST:event_FlechaDerMouseEntered

    private void FlechaDerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlechaDerMouseExited
        utilidades.reescala(FlechaDer, rutaFlechas[1], tamañoFlechas);
    }//GEN-LAST:event_FlechaDerMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnComenzar;
    private static javax.swing.JLabel ContentEmbarque;
    private javax.swing.JLabel FlechaDer;
    private javax.swing.JLabel FlechaIzq;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JLabel Linea;
    private javax.swing.JLabel Punto1;
    private javax.swing.JLabel Punto2;
    private javax.swing.JLabel Punto3;
    private javax.swing.JLabel Punto4;
    private javax.swing.JLabel Punto5;
    private javax.swing.JLabel Text;
    private javax.swing.JPanel basePuntos;
    private javax.swing.JPanel bgGame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


}
